# Generated by Django 4.1 on 2022-12-16 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item', models.CharField(choices=[('ThumsUp', 'ThumsUp'), ('Sprite', 'Sprite'), ('Pepsi', 'Pepsi'), ('Maaja', 'Maaja'), ('Limca', 'Limca')], max_length=100)),
                ('Volume', models.CharField(choices=[('200ml', '200ml'), ('500ml', '500ml'), ('1000ml', '1000ml'), ('2500ml', '2500ml')], max_length=100)),
                ('Quantity', models.IntegerField()),
            ],
        ),
    ]
