# Generated by Django 4.1 on 2022-11-24 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoPractice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyDetailes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Father_Name', models.CharField(max_length=20)),
                ('Mother_Name', models.CharField(max_length=20)),
                ('Son_Name', models.CharField(max_length=20)),
            ],
        ),
    ]
