# Generated by Django 4.1 on 2022-11-12 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestFrameWork', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee_Name', models.CharField(max_length=20)),
                ('Employee_Age', models.IntegerField()),
                ('Employee_Address', models.CharField(max_length=20)),
                ('Employee_Salary', models.IntegerField()),
            ],
        ),
    ]
