# Generated by Django 4.1 on 2022-12-15 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RestFrameWork', '0003_people'),
    ]

    operations = [
        migrations.DeleteModel(
            name='People',
        ),
    ]
