# Generated by Django 4.1 on 2022-12-15 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagination', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='passby',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
