# Generated by Django 4.1 on 2022-11-10 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ganesh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='EmployeeSalary',
            field=models.IntegerField(null=True),
        ),
    ]
