# Generated by Django 4.1 on 2022-11-10 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ganesh', '0002_employee_employeesalary'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='EmployeeDeptNo',
            field=models.IntegerField(null=True),
        ),
    ]
