# Generated by Django 4.1 on 2022-11-10 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ganesh', '0003_employee_employeedeptno'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='EmployeeDeptName',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
