# Generated by Django 4.1 on 2022-11-10 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ganesh', '0005_customer_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='Customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Vehicle', to='Ganesh.customer'),
        ),
    ]
