# Generated by Django 4.1 on 2022-11-10 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ganesh', '0006_alter_vehicle_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='Customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Vehicle', to='Ganesh.customer'),
        ),
        migrations.CreateModel(
            name='Vehicle2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Vehicle2', to='Ganesh.customer2')),
            ],
        ),
    ]
