# Generated by Django 4.1 on 2022-11-10 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ganesh', '0008_vehic_rename_customer2_custom_delete_vehicle2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameModel(
            old_name='Custom',
            new_name='Customer2',
        ),
        migrations.DeleteModel(
            name='Vehic',
        ),
        migrations.AddField(
            model_name='vehicle2',
            name='Customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Vehicle2', to='Ganesh.customer2'),
        ),
    ]
