# Generated by Django 4.1 on 2022-11-10 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ganesh', '0010_customer3_vehicle3'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetailes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentNo', models.IntegerField()),
                ('StudentName', models.CharField(max_length=20)),
                ('FatherName', models.CharField(max_length=20)),
                ('StudentAge', models.IntegerField()),
                ('Address', models.CharField(max_length=20)),
            ],
        ),
    ]
