# Generated by Django 4.1 on 2022-11-10 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ganesh', '0011_studentdetailes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentdetailes',
            old_name='FatherName',
            new_name='Father_Name',
        ),
        migrations.RenameField(
            model_name='studentdetailes',
            old_name='StudentAge',
            new_name='Student_Age',
        ),
        migrations.RenameField(
            model_name='studentdetailes',
            old_name='StudentName',
            new_name='Student_Name',
        ),
        migrations.RenameField(
            model_name='studentdetailes',
            old_name='StudentNo',
            new_name='Student_No',
        ),
    ]
